In [1]:
import pandas as pd
import numpy as np

In [2]:
## Step 3: Fit the Model

In [32]:
## Predictions

In [4]:
heart_data = pd.read_csv('Heart Attack Data.csv')
heart_data.head()

age  sex  total_cholesterol         ldl        hdl  systolic_bp  \
0   57    1         229.463642  175.879129  39.225687   124.070127   
1   58    1         186.464120  128.984916  34.950968    95.492552   
2   37    1         251.300719  152.347592  45.913288    99.519335   
3   55    1         192.058908  116.803684  67.208925   122.460002   
4   53    1         151.203448  107.017396  60.693838   123.022257   

   diastolic_bp  smoking  diabetes  heart_attack  
0     91.378780        0         0             0  
1     64.355040        1         0             0  
2     64.953147        0         1             0  
3     73.821382        0         0             0  
4     81.121946        0         1             0

In [5]:
x = heart_data.drop('heart_attack', axis = 1)
y = heart_data['heart_attack']

In [33]:
# Making Prediction on Classification problem

In [6]:
from sklearn.ensemble import RandomForestClassifier

In [7]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2)

In [8]:
clf = RandomForestClassifier().fit(x_train, y_train)

In [21]:
# 1st Method: Use predict()

In [10]:
y_predicted = clf.predict(x_test)

In [11]:
y_predicted   ## predicted Value

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [12]:
## Comparision 
np.array(y_test)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0])

In [13]:
np.mean(y_predicted == y_test)

np.float64(0.9)

In [20]:
# 2nd Method: Use score()

In [15]:
clf.score(x_test, y_test)

0.9

In [19]:
# 3th Method: use accuracy_score()

In [17]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_predicted)

0.9

In [30]:
clf.predict(x_test)[:5]

array([0, 0, 0, 0, 0])

In [18]:
# 4th method: predict_proba()

In [29]:
clf.predict_proba(x_test)[:5]

array([[1.  , 0.  ],
       [0.99, 0.01],
       [1.  , 0.  ],
       [0.98, 0.02],
       [1.  , 0.  ]])

In [34]:
## Difference between predict() & predict_proba(): predict() only gives us result value while predict_proba() gives us the average of both [0, 1] value. With the help of that we can measure the chances of both values.

In [35]:
# Making Prediction on regression problem

In [36]:
from sklearn.datasets import fetch_california_housing

In [39]:
california = fetch_california_housing()
california_df = pd.DataFrame(california.data, columns = california.feature_names)
california_df

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
...       ...       ...       ...        ...         ...       ...       ...   
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

       Longitude  
0        -122.23  
1        -122.22  
2        -122.24  
3        -122.25  
4        -122.25  
...          ...  
20635    -121.09  
20636    -121.21  
20637    -121.22  
20638    -121.32  
20639    -121.24  

[20640 rows x 8 columns]

In [42]:
from sklearn.ensemble import RandomForestRegressor
np.random.seed(1)

x = california_df.drop('Population', axis = 1)
y = california_df['Population']

x_test, x_train, y_test, y_train = train_test_split(x, y, test_size = 0.2)
regression_model = RandomForestRegressor().fit(x_train, y_train)

In [47]:
# Predictions
predicted_y = regression_model.predict(x_test)
predicted_y[:5]

array([1432.21, 1157.45,  614.9 , 1685.27,  864.54])

In [48]:
# Ground reality
np.array(y_test[:5])

array([ 879.,  971.,   20., 3538.,  750.])

In [51]:
# Comparsion between them (here we need absoulte mean error)
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test, predicted_y )
# lesser the 'mean_absolute_error' value tha better the result

621.2434811046511