In [1]:
import numpy as np

In [2]:
# Arrays

In [3]:
# 1-Dimensional Array (Vector)

In [4]:
arr_1_dem = np.array([1,2,3,4,5])

In [5]:
arr_1_dem

array([1, 2, 3, 4, 5])

In [6]:
# 2-Dimensional Array (Matrix)

In [7]:
arr_2_dem = np.array([[1,2,3,4],[5,6,7,8]])

In [8]:
arr_2_dem

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
# 3-Dimensional Array  (Matrix)   < -- (Two 2D array combines to form the 3D array)  

In [10]:
arr_3_dem = np.array([[[1,2,3],[4,5,6], [7,8,9]],[[11,12,13],[14,15,16], [17,18,19]]])

In [11]:
arr_3_dem

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]]])

In [12]:
# Shape of Array

In [13]:
arr_3_dem.shape

(2, 3, 3)

In [14]:
# (2,3,3) ==> It shows we have 2 Matrix of 3x3 (3 Rows, 3 Columns)

In [15]:
arr_2_dem.shape

(2, 4)

In [16]:
# (2,4)   ==> 2x4 Matrix (2 Rows, 4 Columns)

In [17]:
arr_1_dem.shape

(5,)

In [18]:
# (5,) ==> 5 no. of rows

In [19]:
 # Functions on Array

In [20]:
# ndim : No. of dimensions

In [21]:
arr_3_dem.ndim

3

In [22]:
arr_2_dem.ndim

2

In [23]:
arr_1_dem.ndim

1

In [24]:
# dtype: Define the data type of array

In [25]:
arr_3_dem.dtype

dtype('int64')

In [26]:
# size: No. of enteries in a array

In [27]:
arr_3_dem.size

18

In [28]:
# type() : Define the type of array

In [29]:
type(arr_3_dem)

numpy.ndarray

In [30]:
# Creating a data frame from the matrix

In [31]:
import pandas as pd

In [32]:
df = pd.DataFrame(arr_2_dem)

In [33]:
df

0  1  2  3
0  1  2  3  4
1  5  6  7  8

In [34]:
# Creating Numpy Array

In [35]:
array = np.array([1,2,3,4,5])

In [36]:
array

array([1, 2, 3, 4, 5])

In [37]:
# We can create a array of 3 types automatically. But they contain 1s, 0s or random numbers

In [38]:
# 1) Ones array ==> Values and its data type is float

In [39]:
ones_arr = np.ones((4,5))

In [40]:
ones_arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [41]:
# 2) Zeros array ==> Values and its data type is float

In [42]:
zeros_arr = np.zeros((2,3))

In [43]:
zeros_arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [44]:
# range(): range(start value, end value, step size)

In [45]:
range_arr = np.arange(0,15,2)

In [46]:
range_arr 

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [47]:
# 3) Random(): random.randint(starting value, ending value, size of matrix)

In [48]:
random_arr = np.random.randint(2,16, size = (3,5))

In [49]:
random_arr

array([[15, 14,  5,  4, 10],
       [13, 12, 14,  8,  6],
       [ 3,  6,  5, 11,  3]], dtype=int32)

In [50]:
# rand: its range is auto set from 0 to 1

In [51]:
rand_arr = np.random.rand(3,5)

In [52]:
rand_arr

array([[0.95083359, 0.89143047, 0.20627124, 0.10122728, 0.02089934],
       [0.03363632, 0.60576439, 0.84202086, 0.33046988, 0.41163361],
       [0.72144431, 0.88254622, 0.29377293, 0.57022322, 0.57758885]])

In [53]:
# seed(): used to lock the value

In [54]:
rand_arr.sum()      # >> Its sum is keep chnaging everytime when we run the file

np.float64(7.439762498208784)

In [55]:
np.random.seed(seed = 0)
seed_rand_arr = np.random.rand(4,5)

In [56]:
seed_rand_arr

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ],
       [0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152],
       [0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606],
       [0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215]])

In [57]:
seed_rand_arr.sum()   # Now, it's sum and values are fix

np.float64(11.63109649045195)

In [58]:
# Accessing Element of Matrix

In [59]:
arr_2_dem[0]

array([1, 2, 3, 4])

In [60]:
arr_2_dem[1]

array([5, 6, 7, 8])

In [61]:
arr_3_dem[1]

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [62]:
arr_3_dem[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
# Slicing of matrix  >> [index, row, column]

In [64]:
arr_3_dem[:1]      # show 1 2D array

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [65]:
arr_3_dem[:2, :1]   # show 1 Row

array([[[ 1,  2,  3]],

       [[11, 12, 13]]])

In [66]:
arr_3_dem[:2, :1, :2]   # show 2 Coulmn

array([[[ 1,  2]],

       [[11, 12]]])

In [67]:
random_arr = np.random.randint(10, size = (2,3,3,3))

In [68]:
random_arr

array([[[[2, 3, 8],
         [1, 3, 3],
         [3, 7, 0]],

        [[1, 9, 9],
         [0, 4, 7],
         [3, 2, 7]],

        [[2, 0, 0],
         [4, 5, 5],
         [6, 8, 4]]],


       [[[1, 4, 9],
         [8, 1, 1],
         [7, 9, 9]],

        [[3, 6, 7],
         [2, 0, 3],
         [5, 9, 4]],

        [[4, 6, 4],
         [4, 3, 4],
         [4, 8, 4]]]], dtype=int32)

In [69]:
random_arr[:1,:1,:1,:1]

array([[[[2]]]], dtype=int32)

In [70]:
 # Array Manipulation

In [71]:
arr_1_dem

array([1, 2, 3, 4, 5])

In [72]:
arr_2_dem

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [73]:
# Addition

In [74]:
arr_1_dem[:4] + arr_2_dem  # Make sure that dimension must be same for broadcast(mapping)

array([[ 2,  4,  6,  8],
       [ 6,  8, 10, 12]])

In [75]:
np.add(arr_1_dem[:4], arr_2_dem )

array([[ 2,  4,  6,  8],
       [ 6,  8, 10, 12]])

In [76]:
# Subtraction

In [77]:
arr_1_dem[:4] - arr_2_dem 

array([[ 0,  0,  0,  0],
       [-4, -4, -4, -4]])

In [78]:
# Multiplication

In [79]:
arr_1_dem[:4] * arr_2_dem 

array([[ 1,  4,  9, 16],
       [ 5, 12, 21, 32]])

In [80]:
# Divison

In [81]:
arr_2_dem[:2, :3] / arr_3_dem[:2, :2, :3]

array([[[1.        , 1.        , 1.        ],
        [1.25      , 1.2       , 1.16666667]],

       [[0.09090909, 0.16666667, 0.23076923],
        [0.35714286, 0.4       , 0.4375    ]]])

In [82]:
# Round Off

In [83]:
arr_2_dem[:2, :3] // arr_3_dem[:2, :2, :3]

array([[[1, 1, 1],
        [1, 1, 1]],

       [[0, 0, 0],
        [0, 0, 0]]])

In [84]:
# Power

In [85]:
arr_2_dem**2

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [86]:
# Square

In [87]:
np.square(arr_2_dem)

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [88]:
# Modullo

In [89]:
arr_2_dem % 2

array([[1, 0, 1, 0],
       [1, 0, 1, 0]])

In [90]:
# Aggregasion

In [91]:
testing_arr = np.random.random(1000)

In [92]:
testing_arr[:10]

array([0.24442559, 0.15896958, 0.11037514, 0.65632959, 0.13818295,
       0.19658236, 0.36872517, 0.82099323, 0.09710128, 0.83794491])

In [93]:
# Sum

In [94]:
sum(testing_arr)            # Python Method

np.float64(493.23479601723744)

In [95]:
%timeit sum(testing_arr)        # Slower

215 μs ± 13.9 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [96]:
np.sum(testing_arr)           # Numpy Method

np.float64(493.2347960172372)

In [97]:
%timeit np.sum(testing_arr)      # Faster

9.76 μs ± 240 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [98]:
# Max

In [99]:
np.max(testing_arr)  

np.float64(0.9998085781169653)

In [100]:
# Min

In [101]:
np.min(testing_arr)  

np.float64(0.0005459648969956543)

In [108]:
# Transpose

In [109]:
arr_2_dem.shape

(2, 4)

In [110]:
arr_2_dem.T.shape

(4, 2)

In [111]:
arr_2_dem.T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [112]:
# Reshape

In [117]:
arr_2_dem.reshape(3,1,1).shape()  

ValueError: cannot reshape array of size 8 into shape (3,1,1)