In [1]:
import numpy as np

In [2]:
# Comparsion

In [6]:
arr1 = np.array([[1,2,3],[3,4,5]])
arr2 = np.array([[1,2,3],[7,8,10]])

In [7]:
arr1

array([[1, 2, 3],
       [3, 4, 5]])

In [8]:
arr2

array([[ 1,  2,  3],
       [ 7,  8, 10]])

In [3]:
# > Greater than

In [9]:
arr1 > arr2

array([[False, False, False],
       [False, False, False]])

In [10]:
arr1 > 5

array([[False, False, False],
       [False, False, False]])

In [11]:
# < Less Than

In [12]:
arr1 < arr2

array([[False, False, False],
       [ True,  True,  True]])

In [13]:
arr1 < 4

array([[ True,  True,  True],
       [ True, False, False]])

In [14]:
# == Equal To

In [15]:
arr1 == arr2

array([[ True,  True,  True],
       [False, False, False]])

In [16]:
arr1 == 1

array([[ True, False, False],
       [False, False, False]])

In [19]:
# >= Greater Than and Equal To

In [18]:
arr1 >= arr2

array([[ True,  True,  True],
       [False, False, False]])

In [20]:
# <= Less Than and Equal To

In [21]:
arr1 <= arr2

array([[ True,  True,  True],
       [ True,  True,  True]])

In [23]:
arr1 <= 3

array([[ True,  True,  True],
       [ True, False, False]])

In [24]:
## != Not Equal To

In [25]:
arr1 != arr2

array([[False, False, False],
       [ True,  True,  True]])