In [1]:
import numpy as np

In [2]:
# Martix Multiplication: 1) Dot Product  2) Element wise Multiplication

In [4]:
np.random.seed(seed =0)
matrix_1 = np.random.randint(10, size= (3,4))
matrix_2 = np.random.randint(10, size= (3,4))

In [5]:
matrix_1

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]], dtype=int32)

In [6]:
matrix_2

array([[8, 8, 1, 6],
       [7, 7, 8, 1],
       [5, 9, 8, 9]], dtype=int32)

In [7]:
# Elemnt wise Multiplication

In [8]:
matrix_1 * matrix_2

array([[40,  0,  3, 18],
       [49, 63, 24,  5],
       [10, 36, 56, 54]], dtype=int32)

In [9]:
# Dot Multiplication      >> M1(r1,c1).M2(r2,c2)   Here must be c1==r2

In [12]:
matrix_1.dot(matrix_2.T)     # Took Transpose of M2 as c1!=r2

array([[ 61,  62,  76],
       [161, 141, 185],
       [ 91, 104, 156]], dtype=int32)