In [6]:
import numpy as np

In [7]:
arr = np.random.seed(seed=0)
arr = np.random.randint(20, size =(5,3))

In [8]:
arr

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]], dtype=int32)

In [9]:
# Sorting

In [10]:
np.sort(arr)       # by default it sort the rows

array([[ 0, 12, 15],
       [ 3,  3,  7],
       [ 9, 18, 19],
       [ 4,  6, 12],
       [ 1,  6,  7]], dtype=int32)

In [11]:
np.sort(arr, axis = 1)     # axis =1 for sorting rows

array([[ 0, 12, 15],
       [ 3,  3,  7],
       [ 9, 18, 19],
       [ 4,  6, 12],
       [ 1,  6,  7]], dtype=int32)

In [12]:
np.sort(arr, axis = 0)   # axis = 0 for sorting columns

array([[ 1,  3,  0],
       [ 3,  6,  7],
       [ 4,  6,  7],
       [ 9, 15, 12],
       [12, 19, 18]], dtype=int32)

In [13]:
np.argsort(arr)  # it give the sorting index number"

array([[2, 0, 1],
       [0, 1, 2],
       [0, 2, 1],
       [0, 1, 2],
       [0, 1, 2]])

In [14]:
np.argmin(arr)  # give the index of smallest number

np.int64(2)

In [15]:
np.argmin(arr, axis = 1) # give the index of smallest number in each row

array([2, 0, 0, 0, 0])

In [16]:
np.argmin(arr, axis = 0) # give the index of smallest number in coumn

array([4, 1, 0])

In [19]:
np.argmax(arr, axis = 1)  # give the index of largest number in each row

array([1, 2, 1, 2, 2])

In [20]:
np.argmax(arr, axis = 0)   # give the index of largest number in column

array([0, 2, 2])