In [1]:
import numpy as np

In [2]:
# Show addition using Dot product

In [3]:
item_amount = np.random.seed(seed=0)
item_amount = np.random.randint(20, size =(5,3))

In [33]:
item_amount

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]], dtype=int32)

In [34]:
item_price = np.array([20, 40 ,50])

In [35]:
item_price

array([20, 40, 50])

In [36]:
item_price.reshape(3,1)

array([[20],
       [40],
       [50]])

In [37]:
import pandas as pd

In [38]:
new_item_price = pd.DataFrame(item_price.reshape(1,3), index=['Prices'], columns = ['item1', 'item2', 'item3'])

In [40]:
new_item_price.shape

(1, 3)

In [42]:
total_price = new_item_price.dot(item_amount.T)

In [39]:
new_item_price

item1  item2  item3
Prices     20     40     50

In [41]:
item_amount.shape

(5, 3)

In [43]:
total_price

0    1     2    3    4
Prices  840  530  1840  920  610

In [44]:
new_item_amount = pd.DataFrame(total_price, index=['Mon','Tue','Wed','Thus','Fri',], columns = ['Price'])

In [45]:
new_item_amount

Price
Mon     NaN
Tue     NaN
Wed     NaN
Thus    NaN
Fri     NaN

In [46]:
total_item = new_item_amount.dot(new_item_price.T)

ValueError: matrices are not aligned

In [47]:
total_item

Prices
Mon      840
Tue      530
Wed     1840
Thus     920
Fri      610